import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const root = resolve('apps/web/public/atelier/v2');
const manifest = { assets: [2, 3].flatMap(version => JSON.parse(readFileSync(resolve('apps/web/public/atelier/v' + version, 'manifest.json'), 'utf8')).assets.map(asset => ({ ...asset, file: '/atelier/v' + version + '/' + asset.file }))) };
const entries = manifest.assets.filter(a => a.review.status === 'accepted-concept').map(a => ({
  id: a.id, file: a.file, view: a.view,
  title: Object.entries(a.patch).filter(([key]) => key !== 'twoNames').map(([key, value]) => key === 'size' ? value + ' mm' : value).join(' · '),
  group: a.patch.script === 'Arabic' ? 'Arabic' : a.patch.construction ? 'Construction' : a.patch.lettering ? 'Lettering' : a.patch.twoNames ? 'Two names' : a.patch.metal ? 'Gold' : a.patch.coverage ? 'Stones' : a.patch.chain ? 'Chain' : 'Size',
}));
const safe = JSON.stringify(entries).replaceAll('<', '\\u003c');
const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CALEUMS — Asma studies</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f8f5ee;color:#22211d;font:15px Arial,sans-serif}header,main{max-width:1500px;margin:auto;padding:28px}header{border-bottom:1px solid #d8d0c0}nav{display:flex;justify-content:space-between;gap:20px;align-items:center}.brand{font:28px Georgia;letter-spacing:3px}a{color:inherit}h1{font:clamp(32px,4vw,52px) Georgia;margin:42px 0 12px}.intro{color:#655e51;line-height:1.6;max-width:650px}.filters{display:flex;flex-wrap:wrap;gap:8px;margin:20px 0}button,input{font:16px Arial;min-height:44px;border:1px solid #cfc5b1;background:#fffcf5;color:#22211d;border-radius:4px;padding:10px 14px}button{cursor:pointer}button[aria-pressed=true]{background:#22211d;color:#fff}input{width:min(100%,440px)}:focus-visible{outline:3px solid #9b8148;outline-offset:3px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:24px}.card{min-width:0}.card button{padding:0;border:0;width:100%;display:block;background:#eae1d0}.card img{width:100%;aspect-ratio:4/5;object-fit:cover;display:block}.card h2{font:19px Georgia;line-height:1.4;margin:12px 0 4px}.card p{font-size:12px;color:#655e51;margin:0}.count{color:#655e51;margin:10px 0 24px}dialog{border:0;padding:0;max-height:94dvh;max-width:94vw;background:#f8f5ee}dialog::backdrop{background:#15130fd9}dialog img{display:block;max-width:90vw;max-height:80dvh;object-fit:contain}dialog footer{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:12px}dialog strong{font:18px Georgia}@media(max-width:1100px){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:767px){.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}header,main{padding:18px}.card h2{font-size:16px}}@media(max-width:400px){.grid{grid-template-columns:1fr}nav{font-size:12px}.brand{font-size:22px}}</style>
<header><nav><span class="brand">CALEUMS</span><a href="/en/design/new">Back to designing →</a></nav><h1>One name. Many possibilities.</h1><p class="intro">Explore the pre-generated Asma studies. Compare the lettering, gold, settings and arrangements, then open any photograph for a closer look.</p><label for="search">Find a study</label><br><input id="search" type="search" placeholder="Try origami, rose gold, ruby…"><div class="filters" role="group" aria-label="Study categories"></div></header>
<main><p class="count" aria-live="polite"></p><div class="grid"></div></main><dialog aria-label="Study photograph"><img alt=""><footer><strong></strong><button id="close">Close ×</button></footer></dialog>
<script>const entries=${safe};let category='All';const grid=document.querySelector('.grid'),search=document.querySelector('#search'),dialog=document.querySelector('dialog');const groups=['All',...new Set(entries.map(e=>e.group))];for(const group of groups){const button=document.createElement('button');button.textContent=group;button.setAttribute('aria-pressed',group===category);button.onclick=()=>{category=group;document.querySelectorAll('.filters button').forEach(b=>b.setAttribute('aria-pressed',b.textContent===category));render()};document.querySelector('.filters').append(button)}function render(){const filtered=entries.filter(e=>(category==='All'||category===e.group)&&(e.title+' '+e.view+' '+e.group).toLowerCase().includes(search.value.toLowerCase()));grid.replaceChildren();document.querySelector('.count').textContent=filtered.length+' photographs';for(const entry of filtered){const card=document.createElement('article');card.className='card';const button=document.createElement('button');button.setAttribute('aria-label','Inspect '+entry.title+' — '+entry.view);const img=document.createElement('img');img.src=entry.file;img.alt=entry.title+' example';img.loading='lazy';button.append(img);button.onclick=()=>{dialog.querySelector('img').src=entry.file;dialog.querySelector('img').alt=img.alt;dialog.querySelector('strong').textContent=entry.title+' · '+entry.view;dialog.showModal()};const h=document.createElement('h2');h.textContent=entry.title;const p=document.createElement('p');p.textContent=entry.view+' · Asma sample';card.append(button,h,p);grid.append(card)}}search.oninput=render;document.querySelector('#close').onclick=()=>dialog.close();render();</script></html>`;
writeFileSync(resolve(root, 'index.html'), html);
console.log('Gallery: '+entries.length+' accepted photographs.');
