-- Fix the joint between the composed piece_spec clause and the fixed HERO
-- block. `compilePrompt` trims every substituted value, so the trailing space
-- that piece_spec carried was removed and v2 rendered "tiny links.The pendant".
-- The separator now lives in the template, where trimming cannot reach it.
insert into public.prompt_releases(profile,version,template,parsed_variables,change_note,created_by) values
  ('image.packshot',3,'Catalogue photograph of the full necklace against a neutral ivory cream background, both sides of the chain falling from the top of the frame down to the pendant, the two sides hanging with slightly different curves, a soft visible shadow pooling beneath the pendant. The first supplied image is the ONE AND ONLY source for the pendant: the pendant is EXACTLY the black shape shown in it - every stroke, curve and the small fused dots are one solid manufactured piece, present exactly as drawn, the two small hollow rings at the top are the jump rings; do not add, remove, separate or redraw anything. The second supplied image is a style reference ONLY: match its framing, light, colour palette, setting and overall mood, but never copy the pendant, the name, the letterforms or any object from it. {{piece_spec}} The pendant is the hero of the image - the sharpest, most eye-catching element in the frame, nothing competing with it. Real unretouched photograph, faint grain, not a 3D render, no artificial glow. The chain threads INTO both jump rings with no gap. No text, no logos, no watermarks.',array['piece_spec'],'Fix piece_spec separator swallowed by value trimming','system:migration'),
  ('image.worn',3,'A woman wearing the necklace, photographed for a jewellery brand, the pendant resting {{drape}}, its chain draping naturally and slightly unevenly, casting a thin soft shadow on skin and fabric, natural skin texture. The first supplied image is the ONE AND ONLY source for the pendant: the pendant is EXACTLY the black shape shown in it - every stroke, curve and the small fused dots are one solid manufactured piece, present exactly as drawn, the two small hollow rings at the top are the jump rings; do not add, remove, separate or redraw anything. The second supplied image is a style reference ONLY: match its framing, light, colour palette, setting and overall mood, but never copy the pendant, the name, the letterforms or any object from it. {{piece_spec}} The pendant is the hero of the image - the sharpest, most eye-catching element in the frame, nothing competing with it. Real unretouched photograph, faint grain, not a 3D render, no artificial glow. The chain threads INTO both jump rings with no gap. No text, no logos, no watermarks.',array['piece_spec','drape'],'Fix piece_spec separator swallowed by value trimming','system:migration'),
  ('image.macro_gift',3,'Macro product photograph of the necklace laid on a roll of black suede, the chain snaking across the dark textured fabric in a loose natural curve, suede nap and tiny fibre specks resolved near the pendant, deep soft shadow at the edges, shallow depth of field. The first supplied image is the ONE AND ONLY source for the pendant: the pendant is EXACTLY the black shape shown in it - every stroke, curve and the small fused dots are one solid manufactured piece, present exactly as drawn, the two small hollow rings at the top are the jump rings; do not add, remove, separate or redraw anything. The second supplied image is a style reference ONLY: match its framing, light, colour palette, setting and overall mood, but never copy the pendant, the name, the letterforms or any object from it. {{piece_spec}} The pendant is the hero of the image - the sharpest, most eye-catching element in the frame, nothing competing with it. Real unretouched photograph, faint grain, not a 3D render, no artificial glow. The chain threads INTO both jump rings with no gap. No text, no logos, no watermarks.',array['piece_spec'],'Fix piece_spec separator swallowed by value trimming','system:migration'),
  ('image.dark_editorial',3,'Elegant editorial photograph framed on the neck and collarbone of a woman in a midnight-blue satin dress with a modest neckline against a near-black background, one warm directional spotlight on the necklace, everything else in deep soft shadow, natural skin texture. The first supplied image is the ONE AND ONLY source for the pendant: the pendant is EXACTLY the black shape shown in it - every stroke, curve and the small fused dots are one solid manufactured piece, present exactly as drawn, the two small hollow rings at the top are the jump rings; do not add, remove, separate or redraw anything. The second supplied image is a style reference ONLY: match its framing, light, colour palette, setting and overall mood, but never copy the pendant, the name, the letterforms or any object from it. {{piece_spec}} The pendant is the hero of the image - the sharpest, most eye-catching element in the frame, nothing competing with it. Real unretouched photograph, faint grain, not a 3D render, no artificial glow. The chain threads INTO both jump rings with no gap. No text, no logos, no watermarks.',array['piece_spec'],'Fix piece_spec separator swallowed by value trimming','system:migration'),
  ('image.studio_hero',3,'Studio photograph of the necklace hanging in front of a warm ivory-grey seamless paper sweep lit by a single softbox from the upper left with a white bounce card right, asymmetric falloff on the sweep, no radial halo, no props, chain hanging with slightly uneven drape, a soft accurate shadow behind. The first supplied image is the ONE AND ONLY source for the pendant: the pendant is EXACTLY the black shape shown in it - every stroke, curve and the small fused dots are one solid manufactured piece, present exactly as drawn, the two small hollow rings at the top are the jump rings; do not add, remove, separate or redraw anything. The second supplied image is a style reference ONLY: match its framing, light, colour palette, setting and overall mood, but never copy the pendant, the name, the letterforms or any object from it. {{piece_spec}} The pendant is the hero of the image - the sharpest, most eye-catching element in the frame, nothing competing with it. Real unretouched photograph, faint grain, not a 3D render, no artificial glow. The chain threads INTO both jump rings with no gap. No text, no logos, no watermarks.',array['piece_spec'],'Fix piece_spec separator swallowed by value trimming','system:migration'),
  ('image.billboard',3,'Campaign photograph of the necklace hanging toward the right of the frame against a matte black paper sweep lit by one narrow warm spotlight from above, the metal glowing with a subtle rim light, calm empty darkness across the left of the frame, nothing else in frame. The first supplied image is the ONE AND ONLY source for the pendant: the pendant is EXACTLY the black shape shown in it - every stroke, curve and the small fused dots are one solid manufactured piece, present exactly as drawn, the two small hollow rings at the top are the jump rings; do not add, remove, separate or redraw anything. The second supplied image is a style reference ONLY: match its framing, light, colour palette, setting and overall mood, but never copy the pendant, the name, the letterforms or any object from it. {{piece_spec}} The pendant is the hero of the image - the sharpest, most eye-catching element in the frame, nothing competing with it. Real unretouched photograph, faint grain, not a 3D render, no artificial glow. The chain threads INTO both jump rings with no gap. No text, no logos, no watermarks.',array['piece_spec'],'Fix piece_spec separator swallowed by value trimming','system:migration')
on conflict (profile,version) do nothing;

update public.prompt_profile_publications p
set release_id = r.id, published_by = 'system:migration', published_at = now()
from public.prompt_releases r
where r.profile = p.profile and r.version = 3
  and p.profile in ('image.packshot','image.worn','image.macro_gift','image.dark_editorial','image.studio_hero','image.billboard');
